### ISSUE TITLE
Fatal error for wrong credentials when login

### ISSUE THREAD

**Issue by mickaelperrin** [mgm-sp/wp-author-security#1]
Hi,

Some plugins redefine the global `$errors`. I don't know if this is a good thing or not.

Would you mind testing if `$errors` is not null before grabbing `get_error_codes` ?

https://github.com/mgm-sp/wp-author-security/blob/dafaad8ce6858d632c18aec714f4eb4df7f6f6da/wp-author-security/wp-author-security.php#L149

Thanks,

**Comment by developeregrem** [comment]
Hi,
thanks for reporting this! This will be addressed in the next release.
All the best
